### ISSUE TITLE
SEC-4901 - XSS on /#setup/organization/document/<org_ID>

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#102]
XSS on /#setup/organization/document/<org_ID>

Steps to reproduce:
1. Visit this page https://partners.acronis.com/#gallery/documents/assets
2. Upload any document
3. Change the document name to this payload xssGo" onmouseover="confirm(404)
4. Open URL https://partners.acronis.com/#setup/organization/document/<org_ID> and see JS payload executed (set correct <org_ID>)

Fix: Encode untrusted input according to the rendering context

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and JS is getting executed by following the mentions steps.

![Ticket 102](https://user-images.githubusercontent.com/92088937/183897514-484e1276-d6d1-469c-a0ba-6ab994959874.png)

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/51608

fixed in this PR @sunrao @IshantRevclerx

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, I have checked above security issue on the given branch ( https://pr-51608.dvl.amp.vg/ ), JS is still getting executed.
User Name : Security Ishant
Company Name : Automation Testers

![image](https://user-images.githubusercontent.com/92088937/185591949-a9e848ed-e32b-491d-85e6-c3f14c3766db.png)

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/51707
check here

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch (https://pr-51707.dvl.amp.vg/ ) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify the same.

**Comment by prashantjadhav92** [comment]
Verified by the client.
