### ISSUE TITLE
SEC-5736 IDOR to edit all information of partners customers [/api/SaveUser]

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#173]
1. Visit this page with (A) account https://partners.acronis.com/#setup/users/list
2. Try to save any user
3. In the Burp Suite change the JWT token with (B) account in different org.
4. Try to change any data.
5. Now back to (A) account and you will see the info is changed.

Fix Requirements:
It must not be possible to change data of users from other organizations

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, above issue is not getting reproduced at our end.

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, company based user is able to edit other organization based users.

**Comment by shivmishra** [comment]
@PuneetRevclerx please check here https://github.com/MindMatrix/AMP/pull/59074

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, above issue is still getting reproduced on the given PR.

**Comment by shivmishra** [comment]
should be fixed after build

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, above issue is still getting reproduced on the given PR

**Comment by shivmishra** [comment]
check here https://github.com/MindMatrix/AMP/pull/59312

**Comment by PuneetRevclerx** [comment]
@shivmishra sir, @sunrao sir, I have checked above security issue on the given branch (https://pr-59312.dvl.amp.vg/) and it's working as expected now.

**Comment by IshantRevclerx** [comment]
@shivmishra sir, above issue is working fine on mm live but it is still getting reproduced on Acronis Production.

**Comment by shivmishra** [comment]
check on production after new code release, talk to @shaileshtayde when code get updated

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and Its working as expected now.

**Comment by prashantjadhav92** [comment]
Fix has been verified.
