### ISSUE TITLE
#1439408 Stored XSS via opportunity name on report page (01/11/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#7]
Severity: Medium

- go to https://partners.acronis.com/#connections/contacts
- select a user then go to view -> opportunities
- add new record then go to additional info
- put JS code in opportunity name: XSS<script>alert('happy new year')</script>
- then save ... finish
- POC https://partners.acronis.com/#setup/user/stats/98208?ispartner=undefined

**Comment by shaileshtayde** [comment]
@prashantjadhav92 This issue was already addressed and is good on production.

**Comment by prashantjadhav92** [comment]
@PuneetRevclerx @IshantRevclerx can you please reverify this issue as Acronis has mentioned this is not fixed?

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, this issue is already created by me ( https://github.com/MindMatrix/SecurityTracker/issues/144 )
and the issue is fixed on the PR -https://github.com/MindMatrix/AMP/pull/51374.
Once this PR is released the above issue will be fixed automaticaly.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx is this fixed for Acronis?

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir On acronis production contact opporunity page getting crashed so I didn't checked the issue, once the contact opportinity page is working fine i will check the issue.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx do you have any update on this point? Acronis has again reported this same issue.
Please check this as soon as possible as this issue was reported last year.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, On acronis production contact opporunity page getting crashed so I didn't checked the issue, once the contact opportinity page is working fine I will check the issue.

**Comment by manali1109** [comment]
@IshantRevclerx Sir fixed please check on sb

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir I have checked above security Issue on Acronis Production and Its working as expected now.

**Comment by prashantjadhav92** [comment]
I have notified the client.
