### ISSUE TITLE
XSS : JS Getting Executed on Organization Name

### ISSUE THREAD

**Issue by IshantRevclerx** [MindMatrix/SecurityTracker#78]
URL : https://dvl-main.amp.vg/#setup/organizations
User :  Ishant
Company Name : Automation Testers

STR :

1) Go to above URL.and Edit any Organization Name.
2) Type ( "onmouseover=alert(1)// ) with user name "Security 1" in Organization Name Field (e.g- security 1"onmouseover=alert(1)// )
3) Now Login With Super Admin >>Go to Setup>>>click on UserManagement>>>Click on users>>>Select any User and click on Organization in View dropdown>>>Click on ALL button and hover the mouse on edited ( Security1 "onmouseover=alert(1)// ) Organization name
4) JS getting Executed.

![Organization---alert---1](https://user-images.githubusercontent.com/92088937/179518482-81e65153-3f4f-4021-b8b5-3267bd91f98d.png)

**Comment by shivmishra** [comment]
https://github.com/MindMatrix/AMP/pull/51707
check here

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, I have checked above security issue on the given branch ( https://pr-51707.dvl.amp.vg/ ) JS is still getting executed.
![image](https://user-images.githubusercontent.com/92088937/186077288-af3d5c67-5586-4407-976c-16d0313e3631.png)

**Comment by shivmishra** [comment]
should be fixed after branch build

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, I am still facing the same issue on the given branch.

**Comment by shivmishra** [comment]
wil be fixed after build

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51707.dvl.amp.vg/ ) and Its working as expected now.
